In [120]:
import numpy as np
import scipy.linalg as la
from numpy.random import rand

In [2]:
np.random.seed(1234)
A = rand(10,7)
A

array([[0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581,
        0.27259261, 0.27646426],
       [0.80187218, 0.95813935, 0.87593263, 0.35781727, 0.50099513,
        0.68346294, 0.71270203],
       [0.37025075, 0.56119619, 0.50308317, 0.01376845, 0.77282662,
        0.88264119, 0.36488598],
       [0.61539618, 0.07538124, 0.36882401, 0.9331401 , 0.65137814,
        0.39720258, 0.78873014],
       [0.31683612, 0.56809865, 0.86912739, 0.43617342, 0.80214764,
        0.14376682, 0.70426097],
       [0.70458131, 0.21879211, 0.92486763, 0.44214076, 0.90931596,
        0.05980922, 0.18428708],
       [0.04735528, 0.67488094, 0.59462478, 0.53331016, 0.04332406,
        0.56143308, 0.32966845],
       [0.50296683, 0.11189432, 0.60719371, 0.56594464, 0.00676406,
        0.61744171, 0.91212289],
       [0.79052413, 0.99208147, 0.95880176, 0.79196414, 0.28525096,
        0.62491671, 0.4780938 ],
       [0.19567518, 0.38231745, 0.05387369, 0.45164841, 0.98200474,
        0.1239427 , 0.1

In [3]:
#number of dimensions of array of A
np.ndim(A)

2

In [4]:
#number of elements of array
np.size(A)

70

In [5]:
#“size” of array
np.shape(A)

(10, 7)

In [6]:
#get the number of elements of the n-th dimension of array
A.shape[0], A.shape[1]

(10, 7)

In [7]:
#define a 2x3 2D array
B= np.array([[1. ,2. ,3.], [4. ,5. ,6.]])
B

array([[1., 2., 3.],
       [4., 5., 6.]])

In [8]:
#construct a matrix from blocks a, b, c, and d
np.block([A,np.eye(A.shape[0])])

array([[0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581,
        0.27259261, 0.27646426, 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.80187218, 0.95813935, 0.87593263, 0.35781727, 0.50099513,
        0.68346294, 0.71270203, 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.37025075, 0.56119619, 0.50308317, 0.01376845, 0.77282662,
        0.88264119, 0.36488598, 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.61539618, 0.07538124, 0.36882401, 0.9331401 , 0.65137814,
        0.39720258, 0.78873014, 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.31683612, 0.56809865, 0.86912739, 0.436173

In [9]:
A[-1]

array([0.19567518, 0.38231745, 0.05387369, 0.45164841, 0.98200474,
       0.1239427 , 0.1193809 ])

In [10]:
A[1,4]

0.5009951255234587

In [11]:
A[1]

array([0.80187218, 0.95813935, 0.87593263, 0.35781727, 0.50099513,
       0.68346294, 0.71270203])

In [12]:
A[:5]

array([[0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581,
        0.27259261, 0.27646426],
       [0.80187218, 0.95813935, 0.87593263, 0.35781727, 0.50099513,
        0.68346294, 0.71270203],
       [0.37025075, 0.56119619, 0.50308317, 0.01376845, 0.77282662,
        0.88264119, 0.36488598],
       [0.61539618, 0.07538124, 0.36882401, 0.9331401 , 0.65137814,
        0.39720258, 0.78873014],
       [0.31683612, 0.56809865, 0.86912739, 0.43617342, 0.80214764,
        0.14376682, 0.70426097]])

In [13]:
A[-5:]

array([[0.70458131, 0.21879211, 0.92486763, 0.44214076, 0.90931596,
        0.05980922, 0.18428708],
       [0.04735528, 0.67488094, 0.59462478, 0.53331016, 0.04332406,
        0.56143308, 0.32966845],
       [0.50296683, 0.11189432, 0.60719371, 0.56594464, 0.00676406,
        0.61744171, 0.91212289],
       [0.79052413, 0.99208147, 0.95880176, 0.79196414, 0.28525096,
        0.62491671, 0.4780938 ],
       [0.19567518, 0.38231745, 0.05387369, 0.45164841, 0.98200474,
        0.1239427 , 0.1193809 ]])

In [14]:
A[0:3, 4:9]

array([[0.77997581, 0.27259261, 0.27646426],
       [0.50099513, 0.68346294, 0.71270203],
       [0.77282662, 0.88264119, 0.36488598]])

In [15]:
A[np.ix_([1, 3, 4], [0, 2])]

array([[0.80187218, 0.87593263],
       [0.61539618, 0.36882401],
       [0.31683612, 0.86912739]])

In [16]:
A[2:21:2,:]

array([[0.37025075, 0.56119619, 0.50308317, 0.01376845, 0.77282662,
        0.88264119, 0.36488598],
       [0.31683612, 0.56809865, 0.86912739, 0.43617342, 0.80214764,
        0.14376682, 0.70426097],
       [0.04735528, 0.67488094, 0.59462478, 0.53331016, 0.04332406,
        0.56143308, 0.32966845],
       [0.79052413, 0.99208147, 0.95880176, 0.79196414, 0.28525096,
        0.62491671, 0.4780938 ]])

In [17]:
A[ ::2,:]

array([[0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581,
        0.27259261, 0.27646426],
       [0.37025075, 0.56119619, 0.50308317, 0.01376845, 0.77282662,
        0.88264119, 0.36488598],
       [0.31683612, 0.56809865, 0.86912739, 0.43617342, 0.80214764,
        0.14376682, 0.70426097],
       [0.04735528, 0.67488094, 0.59462478, 0.53331016, 0.04332406,
        0.56143308, 0.32966845],
       [0.79052413, 0.99208147, 0.95880176, 0.79196414, 0.28525096,
        0.62491671, 0.4780938 ]])

In [18]:
A[::-1,:]

array([[0.19567518, 0.38231745, 0.05387369, 0.45164841, 0.98200474,
        0.1239427 , 0.1193809 ],
       [0.79052413, 0.99208147, 0.95880176, 0.79196414, 0.28525096,
        0.62491671, 0.4780938 ],
       [0.50296683, 0.11189432, 0.60719371, 0.56594464, 0.00676406,
        0.61744171, 0.91212289],
       [0.04735528, 0.67488094, 0.59462478, 0.53331016, 0.04332406,
        0.56143308, 0.32966845],
       [0.70458131, 0.21879211, 0.92486763, 0.44214076, 0.90931596,
        0.05980922, 0.18428708],
       [0.31683612, 0.56809865, 0.86912739, 0.43617342, 0.80214764,
        0.14376682, 0.70426097],
       [0.61539618, 0.07538124, 0.36882401, 0.9331401 , 0.65137814,
        0.39720258, 0.78873014],
       [0.37025075, 0.56119619, 0.50308317, 0.01376845, 0.77282662,
        0.88264119, 0.36488598],
       [0.80187218, 0.95813935, 0.87593263, 0.35781727, 0.50099513,
        0.68346294, 0.71270203],
       [0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581,
        0.27259261, 0.2

In [19]:
A[np.r_[:len(A),0]]

array([[0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581,
        0.27259261, 0.27646426],
       [0.80187218, 0.95813935, 0.87593263, 0.35781727, 0.50099513,
        0.68346294, 0.71270203],
       [0.37025075, 0.56119619, 0.50308317, 0.01376845, 0.77282662,
        0.88264119, 0.36488598],
       [0.61539618, 0.07538124, 0.36882401, 0.9331401 , 0.65137814,
        0.39720258, 0.78873014],
       [0.31683612, 0.56809865, 0.86912739, 0.43617342, 0.80214764,
        0.14376682, 0.70426097],
       [0.70458131, 0.21879211, 0.92486763, 0.44214076, 0.90931596,
        0.05980922, 0.18428708],
       [0.04735528, 0.67488094, 0.59462478, 0.53331016, 0.04332406,
        0.56143308, 0.32966845],
       [0.50296683, 0.11189432, 0.60719371, 0.56594464, 0.00676406,
        0.61744171, 0.91212289],
       [0.79052413, 0.99208147, 0.95880176, 0.79196414, 0.28525096,
        0.62491671, 0.4780938 ],
       [0.19567518, 0.38231745, 0.05387369, 0.45164841, 0.98200474,
        0.1239427 , 0.1

In [20]:
A.T

array([[0.19151945, 0.80187218, 0.37025075, 0.61539618, 0.31683612,
        0.70458131, 0.04735528, 0.50296683, 0.79052413, 0.19567518],
       [0.62210877, 0.95813935, 0.56119619, 0.07538124, 0.56809865,
        0.21879211, 0.67488094, 0.11189432, 0.99208147, 0.38231745],
       [0.43772774, 0.87593263, 0.50308317, 0.36882401, 0.86912739,
        0.92486763, 0.59462478, 0.60719371, 0.95880176, 0.05387369],
       [0.78535858, 0.35781727, 0.01376845, 0.9331401 , 0.43617342,
        0.44214076, 0.53331016, 0.56594464, 0.79196414, 0.45164841],
       [0.77997581, 0.50099513, 0.77282662, 0.65137814, 0.80214764,
        0.90931596, 0.04332406, 0.00676406, 0.28525096, 0.98200474],
       [0.27259261, 0.68346294, 0.88264119, 0.39720258, 0.14376682,
        0.05980922, 0.56143308, 0.61744171, 0.62491671, 0.1239427 ],
       [0.27646426, 0.71270203, 0.36488598, 0.78873014, 0.70426097,
        0.18428708, 0.32966845, 0.91212289, 0.4780938 , 0.1193809 ]])

In [21]:
C= np.ones(B.shape)+ 1j * np.ones(B.shape)
C.conj().T

array([[1.-1.j, 1.-1.j],
       [1.-1.j, 1.-1.j],
       [1.-1.j, 1.-1.j]])

In [22]:
A @ np.ones(A.shape[1])

array([3.36574721, 4.89092152, 3.46865235, 3.83005239, 3.84041103,
       3.44379406, 2.78459675, 3.32432816, 4.92163296, 2.30884306])

In [30]:
A * 0.5

array([[0.09575973, 0.31105439, 0.21886387, 0.39267929, 0.3899879 ,
        0.1362963 , 0.13823213],
       [0.40093609, 0.47906968, 0.43796632, 0.17890863, 0.25049756,
        0.34173147, 0.35635101],
       [0.18512538, 0.28059809, 0.25154158, 0.00688422, 0.38641331,
        0.4413206 , 0.18244299],
       [0.30769809, 0.03769062, 0.184412  , 0.46657005, 0.32568907,
        0.19860129, 0.39436507],
       [0.15841806, 0.28404933, 0.43456369, 0.21808671, 0.40107382,
        0.07188341, 0.35213049],
       [0.35229065, 0.10939605, 0.46243381, 0.22107038, 0.45465798,
        0.02990461, 0.09214354],
       [0.02367764, 0.33744047, 0.29731239, 0.26665508, 0.02166203,
        0.28071654, 0.16483422],
       [0.25148342, 0.05594716, 0.30359685, 0.28297232, 0.00338203,
        0.30872085, 0.45606144],
       [0.39526207, 0.49604073, 0.47940088, 0.39598207, 0.14262548,
        0.31245835, 0.2390469 ],
       [0.09783759, 0.19115873, 0.02693684, 0.2258242 , 0.49100237,
        0.06197135, 0.0

In [31]:
A/2

array([[0.09575973, 0.31105439, 0.21886387, 0.39267929, 0.3899879 ,
        0.1362963 , 0.13823213],
       [0.40093609, 0.47906968, 0.43796632, 0.17890863, 0.25049756,
        0.34173147, 0.35635101],
       [0.18512538, 0.28059809, 0.25154158, 0.00688422, 0.38641331,
        0.4413206 , 0.18244299],
       [0.30769809, 0.03769062, 0.184412  , 0.46657005, 0.32568907,
        0.19860129, 0.39436507],
       [0.15841806, 0.28404933, 0.43456369, 0.21808671, 0.40107382,
        0.07188341, 0.35213049],
       [0.35229065, 0.10939605, 0.46243381, 0.22107038, 0.45465798,
        0.02990461, 0.09214354],
       [0.02367764, 0.33744047, 0.29731239, 0.26665508, 0.02166203,
        0.28071654, 0.16483422],
       [0.25148342, 0.05594716, 0.30359685, 0.28297232, 0.00338203,
        0.30872085, 0.45606144],
       [0.39526207, 0.49604073, 0.47940088, 0.39598207, 0.14262548,
        0.31245835, 0.2390469 ],
       [0.09783759, 0.19115873, 0.02693684, 0.2258242 , 0.49100237,
        0.06197135, 0.0

In [32]:
A**3

array([[7.02487596e-03, 2.40768115e-01, 8.38710745e-02, 4.84399833e-01,
        4.74507846e-01, 2.02554647e-02, 2.11308499e-02],
       [5.15603000e-01, 8.79601649e-01, 6.72066304e-01, 4.58124896e-02,
        1.25747831e-01, 3.19260289e-01, 3.62012846e-01],
       [5.07560548e-02, 1.76743777e-01, 1.27326662e-01, 2.61008780e-06,
        4.61579191e-01, 6.87626449e-01, 4.85815698e-02],
       [2.33058198e-01, 4.28341211e-04, 5.01715527e-02, 8.12532164e-01,
        2.76375503e-01, 6.26666061e-02, 4.90665266e-01],
       [3.18056348e-02, 1.83345932e-01, 6.56523550e-01, 8.29807969e-02,
        5.16134552e-01, 2.97150209e-03, 3.49301832e-01],
       [3.49778695e-01, 1.04735749e-02, 7.91113393e-01, 8.64334099e-02,
        7.51872914e-01, 2.13946150e-04, 6.25870805e-03],
       [1.06195275e-04, 3.07384168e-01, 2.10246614e-01, 1.51683933e-01,
        8.13181569e-05, 1.76967695e-01, 3.58287900e-02],
       [1.27238354e-01, 1.40095471e-03, 2.23862724e-01, 1.81268299e-01,
        3.09472980e-07, 2

In [33]:
(A > 0.5)

array([[False,  True, False,  True,  True, False, False],
       [ True,  True,  True, False,  True,  True,  True],
       [False,  True,  True, False,  True,  True, False],
       [ True, False, False,  True,  True, False,  True],
       [False,  True,  True, False,  True, False,  True],
       [ True, False,  True, False,  True, False, False],
       [False,  True,  True,  True, False,  True, False],
       [ True, False,  True,  True, False,  True,  True],
       [ True,  True,  True,  True, False,  True, False],
       [False, False, False, False,  True, False, False]])

In [34]:
np.nonzero(A > 0.5)

(array([0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5,
        5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9]),
 array([1, 3, 4, 0, 1, 2, 4, 5, 6, 1, 2, 4, 5, 0, 3, 4, 6, 1, 2, 4, 6, 0,
        2, 4, 1, 2, 3, 5, 0, 2, 3, 5, 6, 0, 1, 2, 3, 5, 4]))

In [48]:
A[:,(rand(A.shape[0]) > 0.5)[0]]

array([[[0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581,
         0.27259261, 0.27646426]],

       [[0.80187218, 0.95813935, 0.87593263, 0.35781727, 0.50099513,
         0.68346294, 0.71270203]],

       [[0.37025075, 0.56119619, 0.50308317, 0.01376845, 0.77282662,
         0.88264119, 0.36488598]],

       [[0.61539618, 0.07538124, 0.36882401, 0.9331401 , 0.65137814,
         0.39720258, 0.78873014]],

       [[0.31683612, 0.56809865, 0.86912739, 0.43617342, 0.80214764,
         0.14376682, 0.70426097]],

       [[0.70458131, 0.21879211, 0.92486763, 0.44214076, 0.90931596,
         0.05980922, 0.18428708]],

       [[0.04735528, 0.67488094, 0.59462478, 0.53331016, 0.04332406,
         0.56143308, 0.32966845]],

       [[0.50296683, 0.11189432, 0.60719371, 0.56594464, 0.00676406,
         0.61744171, 0.91212289]],

       [[0.79052413, 0.99208147, 0.95880176, 0.79196414, 0.28525096,
         0.62491671, 0.4780938 ]],

       [[0.19567518, 0.38231745, 0.05387369, 0.45164841

In [49]:
A[:,(rand(A.shape[0]).T > 0.5)[0]]

array([], shape=(10, 0, 7), dtype=float64)

In [51]:
A[A < 0.5]=0
A

array([[0.        , 0.62210877, 0.        , 0.78535858, 0.77997581,
        0.        , 0.        ],
       [0.80187218, 0.95813935, 0.87593263, 0.        , 0.50099513,
        0.68346294, 0.71270203],
       [0.        , 0.56119619, 0.50308317, 0.        , 0.77282662,
        0.88264119, 0.        ],
       [0.61539618, 0.        , 0.        , 0.9331401 , 0.65137814,
        0.        , 0.78873014],
       [0.        , 0.56809865, 0.86912739, 0.        , 0.80214764,
        0.        , 0.70426097],
       [0.70458131, 0.        , 0.92486763, 0.        , 0.90931596,
        0.        , 0.        ],
       [0.        , 0.67488094, 0.59462478, 0.53331016, 0.        ,
        0.56143308, 0.        ],
       [0.50296683, 0.        , 0.60719371, 0.56594464, 0.        ,
        0.61744171, 0.91212289],
       [0.79052413, 0.99208147, 0.95880176, 0.79196414, 0.        ,
        0.62491671, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.98200474,
        0.        , 0. 

In [52]:
A * (A > 0.5)

array([[0.        , 0.62210877, 0.        , 0.78535858, 0.77997581,
        0.        , 0.        ],
       [0.80187218, 0.95813935, 0.87593263, 0.        , 0.50099513,
        0.68346294, 0.71270203],
       [0.        , 0.56119619, 0.50308317, 0.        , 0.77282662,
        0.88264119, 0.        ],
       [0.61539618, 0.        , 0.        , 0.9331401 , 0.65137814,
        0.        , 0.78873014],
       [0.        , 0.56809865, 0.86912739, 0.        , 0.80214764,
        0.        , 0.70426097],
       [0.70458131, 0.        , 0.92486763, 0.        , 0.90931596,
        0.        , 0.        ],
       [0.        , 0.67488094, 0.59462478, 0.53331016, 0.        ,
        0.56143308, 0.        ],
       [0.50296683, 0.        , 0.60719371, 0.56594464, 0.        ,
        0.61744171, 0.91212289],
       [0.79052413, 0.99208147, 0.95880176, 0.79196414, 0.        ,
        0.62491671, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.98200474,
        0.        , 0. 

In [54]:
A[:] = 3
A

array([[3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.]])

In [55]:
A_prime = A.copy()

In [56]:
y =A[1, :].copy()
y

array([3., 3., 3., 3., 3., 3., 3.])

In [57]:
np.arange(1., 11.)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [58]:
np.arange(10.)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [59]:
np.arange(1.,11.)[:, np.newaxis]

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [60]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
np.zeros((3, 4, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [62]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [65]:
np.eye(3), np.diag(A), np.diag(rand(2), 0)

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([3., 3., 3., 3., 3., 3., 3.]),
 array([[0.27304326, 0.        ],
        [0.        , 0.97449514]]))

In [66]:
np.linspace(1,3,4)

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [67]:
np.mgrid[0:9.,0:6.]

array([[[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8.]],

       [[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]]])

In [70]:
np.ix_(np.r_[0:9.],np.r_[0:6.])

(array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]), array([[0., 1., 2., 3., 4., 5.]]))

In [71]:
np.tile(rand(2,2), (1, 3))

array([[0.66778691, 0.25565329, 0.66778691, 0.25565329, 0.66778691,
        0.25565329],
       [0.10831149, 0.77618072, 0.10831149, 0.77618072, 0.10831149,
        0.77618072]])

In [73]:
np.concatenate((rand(1,2),rand(1,2)),1)

array([[0.78247799, 0.76160391, 0.91440311, 0.65862278]])

In [74]:
np.concatenate((rand(1,2),rand(1,2)))

array([[0.56836758, 0.20175569],
       [0.69829638, 0.95219541]])

In [81]:
A.max(), A.max(1), np.maximum(A[0], A[1])

(3.0,
 array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]),
 array([3., 3., 3., 3., 3., 3., 3.]))

In [85]:
np.sqrt(rand(2,2) @ rand(2,2))

array([[1.16987336, 1.17565188],
       [0.94867881, 1.02595515]])

In [88]:
np.logical_and(rand(2,2),rand(2,2)), np.logical_or(rand(2,2),rand(2,2))

(array([[ True,  True],
        [ True,  True]]), array([[ True,  True],
        [ True,  True]]))

In [100]:
A=rand(2,2)
np.linalg.inv(A), np.linalg.pinv(A)

(array([[ 2.34380985, -0.03619229],
        [-0.69370455,  7.06352565]]), array([[ 2.34380985, -0.03619229],
        [-0.69370455,  7.06352565]]))

In [102]:
np.linalg.solve(A, rand(2))

array([1.39830115, 0.33698677])

In [105]:
U, S, Vh = np.linalg.svd(A)
Vh

array([[-0.9991254 , -0.04181426],
       [-0.04181426,  0.9991254 ]])

In [109]:
C = np.linalg.cholesky(A)
C

array([[0.65368477, 0.        ],
       [0.06419798, 0.37103369]])

In [115]:
D,V = np.linalg.eig(A.T@A)
D

array([0.18463778, 0.01982028])

In [117]:
Q,R = np.linalg.qr(A)
R

array([[-0.42935953, -0.01603713],
       [ 0.        ,  0.14089452]])

In [121]:
P,L,U = la.lu(A)
P

array([[1., 0.],
       [0., 1.]])

In [123]:
np.fft.fft(A)

array([[ 0.42949322+0.j,  0.42511435+0.j],
       [ 0.18375263+0.j, -0.09982214+0.j]])

In [124]:
np.fft.ifft(A)

array([[ 0.21474661+0.j,  0.21255718+0.j],
       [ 0.09187631+0.j, -0.04991107+0.j]])

In [125]:
np.sort(A)

array([[0.00218943, 0.42730378],
       [0.04196524, 0.14178738]])

In [126]:
np.array(A).squeeze()

array([[0.42730378, 0.00218943],
       [0.04196524, 0.14178738]])

In [132]:
np.ndarray.flatten(A)

array([0.42730378, 0.00218943, 0.04196524, 0.14178738])

In [137]:
from scipy import signal
x = np.linspace(0, 10, 20, endpoint=False)
y = np.cos(-x**2/6.0)
f = signal.resample(y, 100)
f

array([ 1.        ,  1.23283311,  1.31727019,  1.27302765,  1.14740269,
        0.99913207,  0.88078847,  0.82497964,  0.83806509,  0.90249922,
        0.98614323,  1.05486   ,  1.08402435,  1.06536954,  1.00747904,
        0.93050762,  0.85758366,  0.80620995,  0.78263328,  0.78081837,
        0.78588726,  0.78033048,  0.75048699,  0.69094819,  0.60552319,
        0.50478221,  0.40143727,  0.30548407,  0.22092394,  0.14511765,
        0.0707372 , -0.01068719, -0.10512733, -0.21370903, -0.33240564,
       -0.45366208, -0.56910426, -0.67215691, -0.75955883, -0.83131707,
       -0.88932657, -0.93540864, -0.9696874 , -0.98998822, -0.9924354 ,
       -0.97288395, -0.92847886, -0.85863231, -0.76502853, -0.65074937,
       -0.51903563, -0.37236513, -0.21236454, -0.04065068,  0.13978552,
        0.3233596 ,  0.50154373,  0.66375109,  0.79927642,  0.89960584,
        0.96017029,  0.98077748,  0.96447814,  0.91530208,  0.8358487 ,
        0.7258814 ,  0.58274561,  0.40370101,  0.18940426, -0.05

In [138]:
np.unique(A)

array([0.00218943, 0.04196524, 0.14178738, 0.42730378])